config/routes.rb
Rails.application.routes.draw do
   root 'ml_authors#index'
   
   resources :articles do
      resources :comments
   end
   resources :users

   resources :ml_authors do
      member do
         get 'pull'
      end
   end

end

app/models/article.rb
class Article < ActiveRecord::Base
   has_many :comments, dependent: :destroy
   validates :title, presence: true,
                     length: {minimum: 5}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/ml_author.rb
class MlAuthor < ActiveRecord::Base
   validates :name, presence: true,
                    length: {in: 3..100,
                             too_long: "100 characters is the maximum allowed.",
                             too_short: "We believe the minimum number of
                                 characters for Author name is 3." },
                    uniqueness: {case_sensitive: false},
                    on: :create
   validates :n_appeared, numericality: {only_integer: true,
                                         greater_than: 0}
   validates :affiliation, :country, length: {maximum: 255}

   def self.search(keywords)
      if keywords
         # byebug
         where(['name LIKE ? COLLATE NOCASE', "%#{keywords}%"])
      else
         all
      end
   end

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

   def show
      @article = Article.find(params[:id])
   end

   def index
      @articles = Article.all
   end

   def new
      @article = Article.new
   end

   def edit
      @article = Article.find(params[:id])
   end

   def create
      @article = Article.new(article_params)

      if @article.save
         redirect_to @article
      else
         render 'new'
      end
   end

   def update
      @article = Article.find(params[:id])

      if @article.update(article_params)
         redirect_to @article
      else
         render 'edit'
      end
   end

   def destroy
      @article = Article.find(params[:id])
      @article.destroy

      redirect_to articles_path
   end

   private
      def article_params
         params.require(:article).permit(:title, :text)
      end

end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

   def index
   end 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

   def create
      @article = Article.find(params['article_id'])
      @comment = @article.comments.create(comment_params)
      redirect_to article_path(@article)
   end

   def destroy
      @article = Article.find(params[:article_id])
      @comment = @article.comments.find(params[:id])
      @comment.destroy
      redirect_to article_path(@article)
   end
   
   private
      def comment_params
         params.require(:comment).permit(:commenter, :body)
      end

end

app/controllers/ml_authors_controller.rb
class MlAuthorsController < ApplicationController
   layout "main"

   def index
     @authors = MlAuthor.search(params['user_input']) \
                                    .paginate(:page => params[:page], :per_page => 12) \
                                    .order('n_appeared desc')
     @users = User.all
   end

   def show
     #TODO: show ml author page
     @ml_author = MlAuthor.find(params[:id])
     @users = User.all
   end

   def edit
     #TODO: edit author details
     @ml_author = MlAuthor.find(params[:id])
   end

   def update
      @ml_author = MlAuthor.find(params[:id])
      if @ml_author.update(ml_author_params)
         redirect_to @ml_author
      else
         render 'edit'
      end
   end

   def pull
      # TODO: fetch profile from scholar.google.com
      @ml_author = MlAuthor.find(params[:id])
      # ml_author_gsprofile = gs_pull(@ml_author.name)
      # @ml_author.affiliation = ml_author_gsprofile
      # @ml_author.save
      # after retrieving all info of the author, refresh the show view
      @users = User.all
      render 'show', object: [@ml_author, @users]
   end

   # def sort
   #    @authors = MlAuthor.search(params['user_input']) \
   #                                  .paginate(:page => params[:page], :per_page => 12) \
   #                                  .order(params[:by]+' '+params[:order])
   #    @users = User.all
   #    redirect_to 'index'
   # end

   private
      def ml_author_params
         params.require(:ml_author).permit(:affiliation, :country, :email)
      end

      def gs_pull(author_name)
         # TODO: retrieve gs profile
      end

end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   def index
      @users = User.all
   end

   def new
      @user = User.new
   end

   def show
      @user = User.find(params['id'])
   end

   def edit
   end

   def update
   end

   def create
      uploaded_io = params[:user][:picture]
      pic_path = Rails.root.join('public', 'uploads', uploaded_io.original_filename)
      File.open(pic_path, 'wb') do |file|
        file.write(uploaded_io.read)
      end
      # byebug
      params[:user][:pic_path] = '/uploads/' + uploaded_io.original_filename
      @user = User.new(user_params)
      if @user.save
         redirect_to users_path
      else
         render 'new'
      end
   end

   def destroy
   end

   private
      def user_params
         params.require(:user).permit(:name, :age, :gender, :email, :address, :phone, :pic_path)
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ml_authors_helper.rb
module MlAuthorsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1> Edit article </h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
<%= link_to 'All users', users_path %> |
<%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render 'form' %>
<%= link_to 'go back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'edit', edit_article_path(@article) %> |
<%= link_to 'go back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
   <%= render 'mainNavbar' %>
   <div class="container">
      <%= yield %>
   </div>
</body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myblog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
   <%= render 'mainNavbar' %>
   <div class="container main-body">
      <div class='row'>
         <div class="col-md-9">
            <%= yield %>
         </div>
         <div class="col-md-3">
            <%= yield :sidebar %>
         </div>
      </div>
   </div>
</body>
</html>

app/views/ml_authors/_author.html.erb
<div class="col-md-3">
   <%= image_tag "http://placehold.it/150x200" %>
   <!-- <%= link_to "Edit Profile", edit_ml_author_url(@ml_author), class: 'btn btn-primary' %> -->
</div>
<div class="col-md-6">
   <h4> <%= @ml_author.name %><a href= <%= edit_ml_author_url(@ml_author) %>> <%= fa_icon "pencil" %> </a>
         <a href= <%= pull_ml_author_url(@ml_author) %>> <%= fa_icon "google" %> </a>
   </h4>
   <hr>
   <p>
      <%= fa_icon "university" %> <%= @ml_author.affiliation != 'N/A'? @ml_author.affiliation : 'Unknown' %>
   </p>
   <p>
      <%= fa_icon "globe" %> <%= @ml_author.country != 'N/A'? ISO3166::Country[@ml_author.country].name : 'Unknown'  %>
   </p>
   <p>
      <%= @ml_author.email %>
   </p>
</div>

app/views/ml_authors/_mainNavbar.html.erb
<nav class="navbar navbar-fixed-top navbar-light bg-faded">
   <a class="navbar-brand" href="/">MLWHO</a>
   <ul class="nav navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">How</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">About</a>
    </li>
   </ul>
   <%= form_tag :ml_authors,
                method: "get",
                class: "form-inline pull-xs-right" do %>
      <input type='text' name='user_input' placehold="Search" class="form-control" >
      <%= submit_tag "Search", class: "btn btn-success-outline"%>
   <% end %>
</nav>

app/views/ml_authors/edit.html.erb
<h3> <%= @ml_author.name %> </h3>
<%= form_for @ml_author do |f| %>
<!-- TODO: beautify the form -->
   Affiliation <%= f.text_area :affiliation %><br>
   Country <%= f.country_select :country %><br>
   Email <%= f.text_field :email %><br>
   <%= submit_tag "save" %>
<% end %>
<%= link_to "back", :back %>

app/views/ml_authors/index.html.erb
<!-- <h1>List of Machine Learning Researchers</h1> -->
<!-- <%= link_to "All useres", users_path %> | <%= link_to "All articles", articles_path %> -->

<table id="ml_author_table" class="table table-hover">
  <tr>
    <th class='col-md-3'><%= fa_icon "user", text: 'Name ' %>
      <!-- TODO: <a href="ml_authors/sort/name/asc"><%= fa_icon "sort" %></a> -->
   </th>
    <th class='col-md-7'><%= fa_icon "university", text: 'Affiliation' %>Affiliation</th>
    <!-- <th>Country</th>
    <th>Email</th> -->
    <th class='col-md-2' style="text-align: center;"><%= fa_icon "trophy", text: 'Appeared' %></th>
  </tr>

  <% @authors.each do |author| %>
    <tr>
      <td class='col-md-3'><%= link_to author.name, ml_author_path(author) %></td>
      <td class='col-md-7'><%= author.affiliation %></td>
      <!-- <td><%= author.country %></td>
      <td><%= author.email %></td> -->
      <td class='col-md-2' style="text-align: center;"><%= author.n_appeared %></td>
    </tr>
  <% end %>
</table>
<div class="digg_pagination">
   <%= will_paginate @authors %>
</div>

<% content_for :sidebar do %>
   <ul class="list-group">
      <p>
         All users
      </p>
      <% @users.each do |user| %>
         <li class="list-group-item">
            <%= image_tag user.pic_path, size: "20x20"  %>
            <%= link_to user.name, user_path(user) %></li>
      <% end %>
   </ul>
<% end %>

app/views/ml_authors/show.html.erb
<% content_for :sidebar do %>
   <ul class="list-group">
      <p>
         All users
      </p>
      <% @users.each do |user| %>
         <li class="list-group-item">
            <%= image_tag user.pic_path, size: "20x20"  %>
            <%= link_to user.name, user_path(user) %></li>
      <% end %>
   </ul>
<% end %>

<%= render "author", object: @ml_author %>

app/views/users/_user.html.erb
<div style="border: solid 1px">
   <p> <%= user.name  %> </p>
   <p> <%= user.gender  %> </p>
   <p> <%= user.age  %> </p>
   <p> <%= user.email  %> </p>
   <p> <%= user.address  %> </p>
   <p> <%= user.phone  %> </p>
</div>

app/views/users/index.html.erb
<h1> All Users </h1>
<%= link_to "Register", new_user_path, class: "btn btn-primary" %><br>

<!-- HTML Code -->
<table class='table'>
   <thead>
      <tr>
         <th>Picture</th> <th>Name</th> <th>Gender</th> <th>Age</th>
         <th>Email</th> <th>Address</th> <th>Phone</th>
      </tr>
   </thead>
   <tbody>
      <% @users.each do |user| %>
         <tr>
            <td><%= image_tag user.pic_path, size: "100x100" %></td>
            <td><%= link_to user.name, user_path(user) %></td>
            <td><%= user.gender %></td>
            <td><%= user.age %></td>
            <td><%= user.email %></td>
            <td><%= user.address %></td>
            <td><%= user.phone %></td>
         </tr>
      <% end %>
   </tbody>
</table>

<!-- <%= render partial: "user", collection: @users %> -->

app/views/users/new.html.erb
<h1>Register a new user </h1>
<%= form_for :user, url: users_path do |f| %>
   Profile Picture <%= f.file_field :picture %><br>
   <%= f.hidden_field :pic_path %>
   Name <%= f.text_field :name %><br>
   Age <%= f.text_field :age %><br>
   Gender <%= f.text_field :gender %> <br>
   Email <%= f.text_field :email %><br>
   Address <%= f.text_field :address %> <br>
   Phone <%= f.text_field :phone %><br>
   <%= f.submit "Register"%>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<p><%= @user.address %></p>
<p><%= @user.phone %></p>
<p><%= @user.email %></p>
<%= link_to 'go back', :back %>